// AUTO-GENERATED by tools/gen-files-manifest.mjs - do not edit by hand.
// Regenerate with: npm run files:manifest

export interface PublicFile {
  name: string;
  urlPath: string;
  bytes: number;
  ext: string;
  modified: string;
}

export const generatedAt = "2026-08-05T22:41:56.646Z";

export const publicFiles: PublicFile[] = [
  {
    "name": "field-guide.pdf",
    "urlPath": "/field-guide.pdf",
    "bytes": 419304,
    "ext": "pdf",
    "modified": "2026-07-27T05:49:51.000Z"
  },
  {
    "name": "first-30-days.pdf",
    "urlPath": "/first-30-days.pdf",
    "bytes": 172687,
    "ext": "pdf",
    "modified": "2026-08-05T05:20:37.000Z"
  },
  {
    "name": "hype_index.pdf",
    "urlPath": "/hype_index.pdf",
    "bytes": 75707,
    "ext": "pdf",
    "modified": "2026-08-05T00:11:38.000Z"
  },
  {
    "name": "nobody-tells-you-pm.pdf",
    "urlPath": "/nobody-tells-you-pm.pdf",
    "bytes": 160736,
    "ext": "pdf",
    "modified": "2026-08-05T05:20:41.000Z"
  },
  {
    "name": "parts-ai-takes.pdf",
    "urlPath": "/parts-ai-takes.pdf",
    "bytes": 156180,
    "ext": "pdf",
    "modified": "2026-08-05T05:20:46.000Z"
  }
];
