// AUTO-GENERATED by tools/gen-files-manifest.mjs - do not edit by hand.
// Regenerate with: npm run files:manifest

export interface PublicFile {
  name: string;
  urlPath: string;
  bytes: number;
  ext: string;
  modified: string;
}

export const generatedAt = "2026-09-16T17:42:15.362Z";

export const publicFiles: PublicFile[] = [
  {
    "name": "field-guide.pdf",
    "urlPath": "/field-guide.pdf",
    "bytes": 419304,
    "ext": "pdf",
    "modified": "2026-07-27T05:49:51.000Z"
  },
  {
    "name": "first-30-days.pdf",
    "urlPath": "/first-30-days.pdf",
    "bytes": 172687,
    "ext": "pdf",
    "modified": "2026-08-05T05:20:37.000Z"
  },
  {
    "name": "hype_index.pdf",
    "urlPath": "/hype_index.pdf",
    "bytes": 75707,
    "ext": "pdf",
    "modified": "2026-08-05T00:11:38.000Z"
  },
  {
    "name": "learn-the-business.pdf",
    "urlPath": "/learn-the-business.pdf",
    "bytes": 155790,
    "ext": "pdf",
    "modified": "2026-08-11T21:41:43.000Z"
  },
  {
    "name": "nobody-tells-you-pm.pdf",
    "urlPath": "/nobody-tells-you-pm.pdf",
    "bytes": 160736,
    "ext": "pdf",
    "modified": "2026-08-05T05:20:41.000Z"
  },
  {
    "name": "part-1-find-the-thing.pdf",
    "urlPath": "/part-1-find-the-thing.pdf",
    "bytes": 172990,
    "ext": "pdf",
    "modified": "2026-08-12T18:55:48.000Z"
  },
  {
    "name": "part-2-write-the-rule.pdf",
    "urlPath": "/part-2-write-the-rule.pdf",
    "bytes": 174262,
    "ext": "pdf",
    "modified": "2026-08-12T18:55:53.000Z"
  },
  {
    "name": "part-3-run-it-by-hand.pdf",
    "urlPath": "/part-3-run-it-by-hand.pdf",
    "bytes": 171955,
    "ext": "pdf",
    "modified": "2026-08-12T18:55:57.000Z"
  },
  {
    "name": "part-4-send-it-right.pdf",
    "urlPath": "/part-4-send-it-right.pdf",
    "bytes": 161536,
    "ext": "pdf",
    "modified": "2026-08-12T18:56:01.000Z"
  },
  {
    "name": "part-5-guardrails.pdf",
    "urlPath": "/part-5-guardrails.pdf",
    "bytes": 170333,
    "ext": "pdf",
    "modified": "2026-08-12T18:56:05.000Z"
  },
  {
    "name": "parts-ai-takes.pdf",
    "urlPath": "/parts-ai-takes.pdf",
    "bytes": 156180,
    "ext": "pdf",
    "modified": "2026-08-05T05:20:46.000Z"
  },
  {
    "name": "pm-or-tpm.pdf",
    "urlPath": "/pm-or-tpm.pdf",
    "bytes": 173877,
    "ext": "pdf",
    "modified": "2026-09-05T21:21:24.803Z"
  },
  {
    "name": "product-or-product-marketing.pdf",
    "urlPath": "/product-or-product-marketing.pdf",
    "bytes": 192219,
    "ext": "pdf",
    "modified": "2026-09-06T02:42:16.199Z"
  },
  {
    "name": "product-or-program.pdf",
    "urlPath": "/product-or-program.pdf",
    "bytes": 190872,
    "ext": "pdf",
    "modified": "2026-09-06T02:42:16.165Z"
  },
  {
    "name": "program-delivery-or-product-marketing.pdf",
    "urlPath": "/program-delivery-or-product-marketing.pdf",
    "bytes": 201037,
    "ext": "pdf",
    "modified": "2026-09-06T02:42:53.942Z"
  },
  {
    "name": "program-or-technical-program.pdf",
    "urlPath": "/program-or-technical-program.pdf",
    "bytes": 199187,
    "ext": "pdf",
    "modified": "2026-09-06T02:31:31.419Z"
  },
  {
    "name": "resume.pdf",
    "urlPath": "/resume.pdf",
    "bytes": 378853,
    "ext": "pdf",
    "modified": "2026-08-31T16:14:02.000Z"
  },
  {
    "name": "technical-delivery-or-product-marketing.pdf",
    "urlPath": "/technical-delivery-or-product-marketing.pdf",
    "bytes": 197961,
    "ext": "pdf",
    "modified": "2026-09-06T02:42:53.940Z"
  },
  {
    "name": "the-conference-play.pdf",
    "urlPath": "/the-conference-play.pdf",
    "bytes": 184317,
    "ext": "pdf",
    "modified": "2026-08-11T21:41:47.000Z"
  },
  {
    "name": "the-pitch.pdf",
    "urlPath": "/the-pitch.pdf",
    "bytes": 168270,
    "ext": "pdf",
    "modified": "2026-08-11T21:41:30.000Z"
  },
  {
    "name": "the-pm-loop.pdf",
    "urlPath": "/the-pm-loop.pdf",
    "bytes": 171709,
    "ext": "pdf",
    "modified": "2026-08-11T21:41:34.000Z"
  },
  {
    "name": "the-promotion-case.pdf",
    "urlPath": "/the-promotion-case.pdf",
    "bytes": 169868,
    "ext": "pdf",
    "modified": "2026-08-11T21:41:38.000Z"
  },
  {
    "name": "the-role-breakdown.pdf",
    "urlPath": "/the-role-breakdown.pdf",
    "bytes": 193057,
    "ext": "pdf",
    "modified": "2026-09-05T21:25:14.423Z"
  }
];
